name: Dependency License Scanning

on:
  push:
    branches:
      - master
      - chore/fossa-workflow

defaults:
  run:
    shell: bash

jobs:
  fossa:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download fossa cli
        run: |-
          mkdir -p $HOME/.local/bin
          curl https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | bash -s -- -b $HOME/.local/bin
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Fossa init
        run: fossa init
      - name: Set env
        run: echo "line_number=$(grep -n "project" .fossa.yml | cut -f1 -d:)" >> $GITHUB_ENV
      - name: Configuration
        run: |-
          sed -i "${line_number}s|.*|  project: git@github.com:${GITHUB_REPOSITORY}.git|" .fossa.yml
          cat .fossa.yml
      - name: Upload dependencies
        run: fossa analyze --debug
        env:
          FOSSA_API_KEY: ${{ secrets.FOSSA_API_KEY }}
